// Event fees configuration - Single source of truth for pricing
// This prevents clients from manipulating payment amounts

const eventFees = {
  // Technical Events
  "crack-the-codebase": { baseFee: 30 },
  "code-and-chaos": { baseFee: 50 },
  "website-rebuilding": { baseFee: 50 },
  "blind-typing": { baseFee: 30 },
  "game-dev-battle": { baseFee: 50 },
  "uiux-contest": { baseFee: 50 },
  "animation-contest": { baseFee: 50 },
  "build-ai-3hrs": { baseFee: 50 },
  "ai-prompt-engineering": { baseFee: 50 },
  "ndli-quiz": { baseFee: 30 },
  "ai-escape": { baseFee: 50 },
  "sql-murder-mystery": { baseFee: 30 },
  "simulation-challenge": { baseFee: 30 },
  "kaggle-data-hack": { baseFee: 50 },
  "code-iq-war": { baseFee: 100 },
  "web-exploitation-challenge": { baseFee: 50 },
  "cryptography-warzone": { baseFee: 30 },
  "it-tech-treasure-hunt": { baseFee: 30 },
  "escape-room-tech": { baseFee: 30 },
  "cad-wars": { baseFee: 50 },
  "civil-bidding": { baseFee: 50 },
  "engine-assembly": { baseFee: 100 },
  "product-designing": { baseFee: 50 },
  "circuit-debugging-ece": { baseFee: 50 },
  "vlsi-coding-saga": { baseFee: 100 },
  "volt-client-rapid-quiz": { baseFee: 30 },
  "electro-design-battle": { baseFee: 30 },
  "calibrate-control": { baseFee: 50 },
  "sensor-escape-room": { baseFee: 50 },
  "matlab-simulink": { baseFee: 30 },
  "puzzle-rush": { baseFee: 30 },
  "tictionary": { baseFee: 30 },
  "codemoji": { baseFee: 30 },

  // Non-Technical Events
  "build-battle": { baseFee: 30 },
  "dodge-in-the-dark": { baseFee: 30 },
  "vr-valley": { baseFee: 50 },
  "ping-pong-challenge": { baseFee: 30 },
  "guess-the-song": { baseFee: 30 },
  "foosball": { baseFee: 50 },
  "bottle-beyond-the-line": { baseFee: 30 },
  "fitness-challenge": { baseFee: 30 },
  "escape-room": { baseFee: 50 },
  "minute-to-win-it": { baseFee: 30 },
  "treasure-hunt": { baseFee: 50 },
  "blind-hits": { baseFee: 30 },
  "pyramid-strike": { baseFee: 30 },
  "gaming-arcade": { baseFee: 50 },
  "tech-meme-roasting": { baseFee: 30 },
  "ds-trivias": { baseFee: 30 },
  "silent-signal": { baseFee: 30 },
  "spin-survive": { baseFee: 50 },
  "manhunt": { baseFee: 50 },
  "cold-case": { baseFee: 30 },
  "lights-camera-question": { baseFee: 30 },
  "hoop-hola-shoot": { baseFee: 30 },
  "stick-and-stack": { baseFee: 30 },
  "eee-tambola": { baseFee: 30 },
  "human-circuit": { baseFee: 50 },
  "blind-fold-drawing": { baseFee: 30 },
  "tug-of-war": { baseFee: 30 },
  "reel-or-viral": { baseFee: 30 },
  "archery": { baseFee: 30 },
  "battle-of-arena": { baseFee: 30 },

  // Special Events
  "clay-pot-making": { baseFee: 100 },
  "short-film-festival": { baseFee: 150 },
  "indoor-bowling": { baseFee: 50 },
  "rc-car-race": { baseFee: 100, hasRentalOption: true },
  "polaroid-booth": { baseFee: 50 },
  "box-cricket": { baseFee: 50 },
  "sumo-suit-battle": { baseFee: 100 },
  "shark-tank": { baseFee: 100 },
  "aqua-blast": { baseFee: 40 },
  "line-x": { baseFee: 200, isFeePerTeam: true },
  "reach-it-win-it": { baseFee: 50 },
  "squid-game": { baseFee: 46 },
  "ipl-auction": { baseFee: 30 },

  // Featured Events
  "hackathon": { baseFee: 150 },
  "ideathon": { baseFee: 50 },
  "project-expo": { baseFee: 50 },
  "paper-presentation": { baseFee: 100 },
  "poster-presentation": { baseFee: 50 },

  // Test event
  "test-event": { baseFee: 1 },

  // Flagship
  "startup-or-shut-down": { baseFee: 50 },

};

module.exports = { eventFees };
