// Event fees configuration - Single source of truth for pricing
// This prevents clients from manipulating payment amounts

const eventFees = {
  // Technical Events
  "crack-the-codebase": 30,
  "code-and-chaos": 50,
  "website-rebuilding": 50,
  "blind-typing": 30,
  "game-dev-battle": 50,
  "uiux-contest": 50,
  "animation-contest": 50,
  "build-ai-3hrs": 50,
  "ai-prompt-engineering": 50,
  "ndli-quiz": 30,
  "ai-escape": 50,
  "sql-murder-mystery": 30,
  "simulation-challenge": 30,
  "kaggle-data-hack": 50,
  "code-iq-war": 100,
  "web-exploitation-challenge": 50,
  "cryptography-warzone": 30,
  "it-tech-treasure-hunt": 30,
  "escape-room-tech": 30,
  "cad-wars": 50,
  "civil-bidding": 50,
  "draft-master": 50,
  "product-designing": 50,
  "circuit-debugging-ece": 50,
  "vlsi-coding-saga": 100,
  "volt-client-rapid-quiz": 30,
  "electro-design-battle": 30,
  "calibrate-control": 50,
  "sensor-escape-room": 50,
  "matlab-simulink": 30,
  "puzzle-rush": 30,
  "tictionary": 30,
  "codemoji": 30,

  // Non-Technical Events
  "build-battle": 30,
  "dodge-in-the-dark": 30,
  "vr-valley": 50,
  "ping-pong-challenge": 30,
  "guess-the-song": 30,
  "foosball": 50,
  "bottle-beyond-the-line": 30,
  "fitness-challenge": 30,
  "escape-room": 50,
  "minute-to-win-it": 30,
  "treasure-hunt": 50,
  "blind-hits": 30,
  "pyramid-strike": 30,
  "gaming-arcade": 50,
  "tech-meme-roasting": 30,
  "ds-trivias": 30,
  "silent-signal": 30,
  "spin-survive": 50,
  "manhunt": 50,
  "cold-case": 30,
  "lights-camera-question": 30,
  "hoop-hola-shoot": 30,
  "stick-and-stack": 30,
  "eee-tambola": 30,
  "human-circuit": 50,
  "blind-fold-drawing": 30,
  "tug-of-war": 30,
  "reel-or-viral": 30,
  "archery": 30,
  "battle-of-arena": 30,

  // Special Events
  "clay-pot-making": 100,
  "short-film-festival": 150,
  "indoor-bowling": 50,
  "rc-car-race": 100,
  "polaroid-booth": 50,
  "box-cricket": 50,
  "sumo-suit-battle": 100,
  "shark-tank": 100,
  "aqua-blast": 40,
  "line-x": 200,
  "reach-it-win-it": 50,
  "squid-game": 46,
  "ipl-auction": 30,

  // Featured Events
  "hackathon": 150,
  "ideathon": 50,
  "project-expo": 50,
  "paper-presentation": 100,
  "poster-presentation": 50,

  // Test event
  "test-event": 1,
};

module.exports = { eventFees };
